WebApplication1/Models/DishesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Persistance;

namespace WebApplication1.Models
{
    public class DishesController : Controller
    {
        private LunchDbContext db = new LunchDbContext();

        // GET: Dishes
        public ActionResult Index()
        {
            return View(db.Dishes.ToList());
        }

        // GET: Dishes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dish = db.Dishes.Find(id);
            if (dish == null)
            {
                return HttpNotFound();
            }
            return View(dish);
        }

        // GET: Dishes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Dishes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Price")] Dish dish)
        {
            if (ModelState.IsValid)
            {
                db.Dishes.Add(dish);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dish);
        }

        // GET: Dishes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dish = db.Dishes.Find(id);
            if (dish == null)
            {
                return HttpNotFound();
            }
            return View(dish);
        }

        // POST: Dishes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Price")] Dish dish)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dish).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dish);
        }

        // GET: Dishes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dish = db.Dishes.Find(id);
            if (dish == null)
            {
                return HttpNotFound();
            }
            return View(dish);
        }

        // POST: Dishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dish dish = db.Dishes.Find(id);
            db.Dishes.Remove(dish);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Models/Order.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace WebApplication1.Models
{
    public class Order
    {
        public Order()
        {
            OrderDetails = new List<OrderDetail>();
        }

        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public string Email { get; set; }
        public bool IsServed { get; set; }
        public ICollection<OrderDetail> OrderDetails { get; set; }

        public void AddOrderDetail(int id, int quantity)
        {
            var orderDetail = new OrderDetail();
            orderDetail.DishId = id;
            orderDetail.Quantity = quantity;
            OrderDetails.Add(orderDetail);
        }

        public decimal TotalAmount
        {
            get
            {
                return OrderDetails
                    .Sum(d => d.Quantity * d.Dish.Price);
            }
        }
    }
}

WebApplication1/Models/OrderDetail.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public class OrderDetail
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public int OrderId { get; set; }
        [ForeignKey("OrderId")]
        public Order Order { get; set; }

        public int DishId { get; set; }
        [ForeignKey("DishId")]
        public Dish Dish { get; set; }

        public int Quantity { get; set; }
    }
}

WebApplication1/Models/OrderViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using WebApplication1.Persistence;

namespace WebApplication1.Models
{
    public class OrderViewModel
    {
        public OrderViewModel()
        {
            var dishRepository = new DishRepository();

            Dishes = dishRepository
                .GetAll()
                .Select(d => new DishViewModel
                    {
                        Id = d.Id,
                        Name = d.Name,
                        Price = d.Price
                    })
                .ToList();
        }

        public List<DishViewModel> Dishes { get; set; }

        [EmailAddress(ErrorMessage = "Inte en epostadress.")]
        [Required]
        [DisplayName("E-post")]
        public string Email { get; set; }

        public string QtyErrorMessage { get; set; }
    }
}

WebApplication1/Controllers/AdminController.cs
using System.Web.Mvc;
using WebApplication1.Persistence;

namespace WebApplication1.Controllers
{
    public class AdminController : Controller
    {
        public ActionResult Index()
        {
            var repo = new OrderRepository();
            var pendingOrders = repo.GetPendingOrders();
            return View(pendingOrders);
        }
    }
}

WebApplication1/Controllers/OrderController.cs
using System.Collections.Generic;
using System.Threading;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Persistence;

namespace WebApplication1.Controllers
{
    public class OrderController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Confirm(int? id)
        {
            var orderRepository = new OrderRepository();

            if (id == null)
            {
                return View();
            }

            var order = orderRepository.GetById(id.Value);

            if (order == null)
            {
                return View();
            }

            return View(order);
        }

        public ActionResult GetDishes()
        {
            Thread.Sleep(500);
            var orderViewModel = new OrderViewModel();
            List<DishViewModel> dishes = orderViewModel.Dishes;
            return Json(dishes, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Submit(SubmitOrderModel model)
        {
            var orderRepository = new OrderRepository();
            var order = new Order();
            order.Email = model.Email;
            foreach (var orderedDish in model.Dishes)
            {
                if (orderedDish.Quantity > 0)
                {
                    order.AddOrderDetail(orderedDish.Id, orderedDish.Quantity);
                }
            }

            var orderId = orderRepository.Save(order);

            return Json(new { orderId, confirmLink = Url.Action("Confirm", new { id = orderId }) });
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/fontawesome")
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Beställ mat", "Index", "Order")</li>
                    <li>@Html.ActionLink("Maträtter", "Index", "Dishes")</li>
                    <li>@Html.ActionLink("Beställningar", "Index", "Admin")</li>

                    @if (Session["role"] == null)
                    {
                        <li>@Html.ActionLink("Logga in", "Login", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Logga ut", "Logout", "Account")</li>
                        <li>Hej, @Session["role"]!</li>
                    }

                    <li><a href="/canvas.html">Canvas!</a></li>
                </ul>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

WebApplication1/Views/Shared/_Order.cshtml
@model WebApplication1.Models.Order

<div>
    <div>Order: @Model.Id</div>
    <div>Email: @Model.Email</div>
    <div>
        <ul>
            @foreach (var detail in Model.OrderDetails)
            {
                <li>@Html.Partial("_OrderDetail", detail)</li>
            }
        </ul>
    </div>
</div>

WebApplication1/Views/Shared/_OrderDetail.cshtml
@model WebApplication1.Models.OrderDetail

<div>
    <div>@Model.Quantity x @Model.Dish.Name</div>
</div>